name = "r2-explorer" # 部署后的 worker 叫什么
compatibility_date = "2024-11-06"
main = "src/index.ts"
assets = { directory = "node_modules/r2-explorer/dashboard", binding = "ASSETS", html_handling = "auto-trailing-slash", not_found_handling = "single-page-application" }

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "image" # 绑定的存储桶名称
